pipelines:
  pull-requests:
    '**': # This runs as default for any branch not elsewhere defined.:
      - step:
          name: 'Conventional Commits check'
          image: node:lts
          script:
            - npm i
            - /bin/bash commitlint-pipeline-check.sh
