name: Create Release (job)

on:
  workflow_call:
    inputs:
      release_as:
        # https://github.com/conventional-changelog/standard-version#release-as-a-target-type-imperatively-npm-version-like
        required: true
        type: string
        description: auto, major, minor, or patch
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com/

      - name: Find node_modules cache
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Set up git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Version bump
        env:
          RELEASE_AS: ${{ inputs.release_as }}
        run: |
          npm run build
          if [[ "$RELEASE_AS" == "auto" ]]
          then
            npm run release
          else
            npm run release -- --release-as $RELEASE_AS
          fi

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Commit changes
        run: |
          export VERSION_TAG=$(git describe --tags --abbrev=0)
          git push origin $VERSION_TAG
          git push origin main
