name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm-ci:
    uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@v2.1.0
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

  build:
    needs: [npm-ci]
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build